name: Build&Push

on:
  workflow_call:
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true
      registry_tag:
        required: true
      github_sha:
        required: true
      job_id:
        required: true
      release_version:
        required: true
      env:
        required: true

jobs:
  build_and_push_dev_to_yandex_registry:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:

      - name: Add GITHUB_SHA env property with commit github sha
        run: echo "GITHUB_SHA=`echo ${{ secrets.github_sha }}`" >> $GITHUB_ENV

      - name: Add JOB_ID env property with commit job id
        run: echo "JOB_ID=`echo ${{ secrets.job_id }}`" >> $GITHUB_ENV

      - name: Add JOB_ID env property with commit job id
        run: echo "ENV=`echo ${{ secrets.env }}`" >> $GITHUB_ENV

      - name: Add JOB_ID env property with commit job id
        run: echo "RELEASE_VERSION=`echo ${{ secrets.release_version }}`" >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: ${{ secrets.registry_tag }}
          build-args: |
            GITHUB_SHA=${{ env.GITHUB_SHA }}
            JOB_ID=${{ env.JOB_ID }}
            ENV=${{ env.ENV }}
            RELEASE_VERSION=${{ env.RELEASE_VERSION }}