name: Build&Push

on:
  workflow_call:
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      REGISTRY_TAG:
        required: true
      GITHUB_SHA:
        required: true
      JOB_ID:
        required: true
      ENV:
        required: true

jobs:
  build_and_push_dev_to_yandex_registry:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: ${{ secrets.REGISTRY_TAG }}
          build-args: |
            GITHUB_SHA=${{ secrets.GITHUB_SHA }}
            JOB_ID=${{ secrets.JOB_ID }}
            ENV=${{ secrets.ENV }}