name: Build&Push frontend

on:
  workflow_call:
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true
      registry_tag:
        required: true
      github_sha:
        required: true
      sentry_source_map_job_id:
        required: false
      react_api:
        required: true
      react_ws:
        required: false
      sentry_dsn:
        required: true
      sentry_project_name:
        required: true
      sentry_token:
        required: true
      metrics_counter:
        required: false

jobs:
  build_and_push_to_yandex_registry:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6
          push: true
          file: Dockerfile
          tags: ${{ secrets.registry_tag }}
          build-args: |
            GITHUB_SHA=${{ secrets.github_sha }}
            REACT_APP_API=${{ secrets.react_api }}
            REACT_APP_WS=${{ secrets.react_ws }}
            REACT_APP_SENTRY=${{ secrets.sentry_dsn }}
            SENTRY_TOKEN=${{ secrets.sentry_token }}
            REACT_APP_SENTRY_RELEASE=${{ secrets.sentry_source_map_job_id }}
            REACT_APP_SENTRY_PROJECT=${{ secrets.sentry_project_name }}
            REACT_APP_YANDEX_METRICS_COUNTER=${{ secrets.metrics_counter }}
