name: Deploy

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
    secrets:
      ssh_key:
        required: true
      passphrase:
        required: true
      email_host_password:
        required: true
      db_name:
        required: true
      db_password:
        required: true
      secret_key:
        required: true
      sentry_dsn:
        required: true
      debug_logging_level:
        required: true
      error_logging_level:
        required: true
      server_port:
        required: true
      redis_password:
        required: true
      backed_version:
        required: true
      frontend_version:
        required: true
      registry_id:
        required: true

jobs:
  deploy_preprod_branch:
    name: deploy action
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.ssh_key }}
          passphrase: ${{ secrets.passphrase }}
          script: |
            cd ${{ inputs.directory }}
            echo EMAIL_HOST_PASSWORD=${{ secrets.email_host_password }} > .backend-env
            echo DB_NAME=${{ secrets.db_name }} >> .backend-env
            echo DB_PASSWORD=${{ secrets.db_password }} >> .backend-env
            echo SECRET_KEY=${{ secrets.secret_key }} >> .backend-env
            echo SENTRY_DSN=${{ secrets.sentry_dsn }} >> .backend-env
            echo DEBUG_LOGGING_LEVEL=${{ secrets.debug_logging_level }} >> .backend-env
            echo ERROR_LOGGING_LEVEL=${{ secrets.error_logging_level }} >> .backend-env
            echo SERVER_PORT=${{ secrets.server_port }} >> .backend-env
            echo REDIS_PASSWORD=${{ secrets.redis_password }} >> .backend-env
            echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .backend-env
            echo DB_USER=${{ secrets.DB_USER }} >> .backend-env
            echo DB_HOST=${{ secrets.DB_HOST }} >> .backend-env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .backend-env
            echo EMAIL_HOST=${{ secrets.EMAIL_HOST }} >> .backend-env
            echo EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }} >> .backend-env
            echo EMAIL_PORT=${{ secrets.EMAIL_PORT }} >> .backend-env
            echo SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }} >> .backend-env
            echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .backend-env
            echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .backend-env
            echo CELERY_REDIS_DB=${{ secrets.CELERY_REDIS_DB }} >> .backend-env
            echo BACKEND_VERSION=${{ secrets.backend_version }} > .env
            echo FRONTEND_VERSION=${{ secrets.frontend_version }} >> .env
            echo DB_USER=${{ secrets.db_user }} >> .env
            echo DB_PASSWORD=${{ secrets.db_password }} >> .env
            echo DB_NAME=${{ secrets.db_name }} >> .env
            echo REDIS_PASSWORD=${{ secrets.redis_password }} >> .env
            echo REGISTRY_ID=${{ secrets.registry_id }} >> .env
            echo DB_PORT=${{ secrets.DB_PORT }} >> .env